/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_client/serverpod_client.dart' as _i1;
import 'package:smart_notes_client/src/protocol/protocol.dart' as _i2;

/// A note created by the user, stored in the database with an optional embedding vector for semantic search.
abstract class Note implements _i1.SerializableModel {
  Note._({
    this.id,
    required this.title,
    required this.content,
    this.embedding,
    required this.createdAt,
  });

  factory Note({
    int? id,
    required String title,
    required String content,
    List<double>? embedding,
    required DateTime createdAt,
  }) = _NoteImpl;

  factory Note.fromJson(Map<String, dynamic> jsonSerialization) {
    return Note(
      id: jsonSerialization['id'] as int?,
      title: jsonSerialization['title'] as String,
      content: jsonSerialization['content'] as String,
      embedding: jsonSerialization['embedding'] == null
          ? null
          : _i2.Protocol().deserialize<List<double>>(
              jsonSerialization['embedding'],
            ),
      createdAt: _i1.DateTimeJsonExtension.fromJson(
        jsonSerialization['createdAt'],
      ),
    );
  }

  /// The database id, set if the object has been inserted into the
  /// database or if it has been fetched from the database. Otherwise,
  /// the id will be null.
  int? id;

  /// The title of the note.
  String title;

  /// The main content body of the note.
  String content;

  /// The embedding vector generated by Gemini for semantic search.
  List<double>? embedding;

  /// The time when the note was created.
  DateTime createdAt;

  /// Returns a shallow copy of this [Note]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  Note copyWith({
    int? id,
    String? title,
    String? content,
    List<double>? embedding,
    DateTime? createdAt,
  });
  @override
  Map<String, dynamic> toJson() {
    return {
      '__className__': 'Note',
      if (id != null) 'id': id,
      'title': title,
      'content': content,
      if (embedding != null) 'embedding': embedding?.toJson(),
      'createdAt': createdAt.toJson(),
    };
  }

  @override
  String toString() {
    return _i1.SerializationManager.encode(this);
  }
}

class _Undefined {}

class _NoteImpl extends Note {
  _NoteImpl({
    int? id,
    required String title,
    required String content,
    List<double>? embedding,
    required DateTime createdAt,
  }) : super._(
         id: id,
         title: title,
         content: content,
         embedding: embedding,
         createdAt: createdAt,
       );

  /// Returns a shallow copy of this [Note]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  @override
  Note copyWith({
    Object? id = _Undefined,
    String? title,
    String? content,
    Object? embedding = _Undefined,
    DateTime? createdAt,
  }) {
    return Note(
      id: id is int? ? id : this.id,
      title: title ?? this.title,
      content: content ?? this.content,
      embedding: embedding is List<double>?
          ? embedding
          : this.embedding?.map((e0) => e0).toList(),
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
